app_mode = "development"
[etcd]
addr = ["120.24.24.191:2379"]
logKey = "Log-Collection/logAgent/log"

[mysql]
ip = "localhost"
port = 3306
root = "root"
password = "mysql"

[kafka]
addr = ["120.24.24.191:9092"]
maxSize = 1000
